import * as core from "@actions/core";
import * as github from "@actions/github";
import OpenAI from "openai";
import { components } from "@octokit/openapi-types";

type PullRequestFile = components["schemas"]["diff-entry"];

async function run(): Promise<void> {
  try {
    const githubToken = core.getInput("github_token", { required: true });
    const openaiKey = core.getInput("openai_api_key", { required: true });
    const model = core.getInput("model") || "gpt-4o-mini";

    const octokit = github.getOctokit(githubToken);
    const context = github.context;

    if (context.eventName !== "pull_request") {
      core.info("This action only runs on pull_request events.");
      return;
    }

    const { owner, repo } = context.repo;
    const prNumber = context.payload.pull_request?.number;

    if (!prNumber) {
      core.setFailed("Pull request number not found.");
      return;
    }

    core.info(`Fetching files for PR #${prNumber}`);

    const { data } = await octokit.rest.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100
    });

    const files = data as PullRequestFile[];

    const patches = files
      .filter((file) => file.patch)
      .map((file) => `File: ${file.filename}\n${file.patch}`)
      .join("\n\n");

    if (!patches) {
      core.info("No patch content found to review.");
      return;
    }

    // Protect against extremely large PRs
    const MAX_CHARS = 120000;
    const trimmedDiff =
      patches.length > MAX_CHARS
        ? patches.substring(0, MAX_CHARS) +
          "\n\n[Diff truncated due to size]"
        : patches;

    core.info("Sending diff to OpenAI for review...");

    const openai = new OpenAI({ apiKey: openaiKey });

    const response = await openai.chat.completions.create({
      model,
      messages: [
        {
          role: "system",
          content:
            "You are a senior software architect performing a strict enterprise-grade code review. Provide structured feedback with severity levels (Critical, Major, Minor, Suggestion)."
        },
        {
          role: "user",
          content: `Review the following pull request diff:\n\n${trimmedDiff}`
        }
      ],
      temperature: 0.2
    });

    const reviewComment =
      response.choices?.[0]?.message?.content ||
      "No review generated by AI.";

    core.info("Posting review comment to PR...");

    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: `## 🤖 AI Code Review\n\n${reviewComment}`
    });

    core.info("✅ AI review posted successfully.");
  } catch (error: unknown) {
    if (error instanceof Error) {
      core.setFailed(`Action failed: ${error.message}`);
    } else {
      core.setFailed("Action failed due to an unknown error.");
    }
  }
}

run();